[profile.default]
optimizer = true
optimizer_runs = 3000
src = "src"
out = "out"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
  "../contracts",
]
remappings = [
  "ds-test/=./node_modules/ds-test/src/",
  "forge-std/=./node_modules/forge-std/src/",
  "@geo-web/=./node_modules/@geo-web/",
  "@latticexyz/=./node_modules/@latticexyz/"
]

[profile.local]
eth_rpc_url = "http://127.0.0.1:1248"
[profile.op-goerli]
eth_rpc_url = "https://optimism-goerli.publicnode.com"

