// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x0000000100000000000000000000000000000000000000000000000000000000
);

library Augments {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](2);
    _keySchema[0] = SchemaType.ADDRESS;
    _keySchema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](1);
    _valueSchema[0] = SchemaType.STRING;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "augmentAddress";
    keyNames[1] = "argumentsHash";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "augmentMetadataURI";
  }

  /**
   * @notice Register the table with its config.
   */
  function register(ResourceId _tableId) internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register(ResourceId _tableId) internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config (using the specified store).
   */
  function register(IStore _store, ResourceId _tableId) internal {
    _store.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get augmentMetadataURI.
   */
  function getAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (string memory augmentMetadataURI) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get augmentMetadataURI.
   */
  function _getAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (string memory augmentMetadataURI) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get augmentMetadataURI (using the specified store).
   */
  function getAugmentMetadataURI(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (string memory augmentMetadataURI) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes memory _blob = _store.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get augmentMetadataURI.
   */
  function get(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (string memory augmentMetadataURI) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get augmentMetadataURI.
   */
  function _get(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (string memory augmentMetadataURI) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get augmentMetadataURI (using the specified store).
   */
  function get(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (string memory augmentMetadataURI) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes memory _blob = _store.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set augmentMetadataURI.
   */
  function setAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    string memory augmentMetadataURI
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((augmentMetadataURI)));
  }

  /**
   * @notice Set augmentMetadataURI.
   */
  function _setAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    string memory augmentMetadataURI
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((augmentMetadataURI)));
  }

  /**
   * @notice Set augmentMetadataURI (using the specified store).
   */
  function setAugmentMetadataURI(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    string memory augmentMetadataURI
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    _store.setDynamicField(_tableId, _keyTuple, 0, bytes((augmentMetadataURI)));
  }

  /**
   * @notice Set augmentMetadataURI.
   */
  function set(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    string memory augmentMetadataURI
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((augmentMetadataURI)));
  }

  /**
   * @notice Set augmentMetadataURI.
   */
  function _set(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    string memory augmentMetadataURI
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((augmentMetadataURI)));
  }

  /**
   * @notice Set augmentMetadataURI (using the specified store).
   */
  function set(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    string memory augmentMetadataURI
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    _store.setDynamicField(_tableId, _keyTuple, 0, bytes((augmentMetadataURI)));
  }

  /**
   * @notice Get the length of augmentMetadataURI.
   */
  function lengthAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of augmentMetadataURI.
   */
  function _lengthAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of augmentMetadataURI (using the specified store).
   */
  function lengthAugmentMetadataURI(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    uint256 _byteLength = _store.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of augmentMetadataURI.
   */
  function length(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of augmentMetadataURI.
   */
  function _length(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of augmentMetadataURI (using the specified store).
   */
  function length(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    uint256 _byteLength = _store.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of augmentMetadataURI.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of augmentMetadataURI.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of augmentMetadataURI (using the specified store).
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemAugmentMetadataURI(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _blob = _store.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of augmentMetadataURI.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItem(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of augmentMetadataURI.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItem(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of augmentMetadataURI (using the specified store).
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItem(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _blob = _store.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to augmentMetadataURI.
   */
  function pushAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to augmentMetadataURI.
   */
  function _pushAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to augmentMetadataURI (using the specified store).
   */
  function pushAugmentMetadataURI(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    _store.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to augmentMetadataURI.
   */
  function push(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to augmentMetadataURI.
   */
  function _push(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to augmentMetadataURI (using the specified store).
   */
  function push(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    _store.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from augmentMetadataURI.
   */
  function popAugmentMetadataURI(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from augmentMetadataURI.
   */
  function _popAugmentMetadataURI(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from augmentMetadataURI (using the specified store).
   */
  function popAugmentMetadataURI(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    _store.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from augmentMetadataURI.
   */
  function pop(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from augmentMetadataURI.
   */
  function _pop(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from augmentMetadataURI (using the specified store).
   */
  function pop(IStore _store, ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    _store.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of augmentMetadataURI at `_index`.
   */
  function updateAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of augmentMetadataURI at `_index`.
   */
  function _updateAugmentMetadataURI(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of augmentMetadataURI (using the specified store) at `_index`.
   */
  function updateAugmentMetadataURI(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      _store.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of augmentMetadataURI at `_index`.
   */
  function update(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of augmentMetadataURI at `_index`.
   */
  function _update(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of augmentMetadataURI (using the specified store) at `_index`.
   */
  function update(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    uint256 _index,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      _store.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys (using the specified store).
   */
  function deleteRecord(IStore _store, ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    _store.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory augmentMetadataURI) internal pure returns (PackedCounter _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = PackedCounterLib.pack(bytes(augmentMetadataURI).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory augmentMetadataURI) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((augmentMetadataURI)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(string memory augmentMetadataURI) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData;
    PackedCounter _encodedLengths = encodeLengths(augmentMetadataURI);
    bytes memory _dynamicData = encodeDynamic(augmentMetadataURI);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(address augmentAddress, bytes32 argumentsHash) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    return _keyTuple;
  }
}
