// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { RESOURCE_TABLE, RESOURCE_OFFCHAIN_TABLE } from "@latticexyz/store/src/storeResourceTypes.sol";

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x0010010010000000000000000000000000000000000000000000000000000000
);

library InstalledAugments {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](2);
    _keySchema[0] = SchemaType.ADDRESS;
    _keySchema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](1);
    _valueSchema[0] = SchemaType.BYTES16;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "augmentAddress";
    keyNames[1] = "argumentsHash";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "augmentName";
  }

  /**
   * @notice Register the table with its config.
   */
  function register(ResourceId _tableId) internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register(ResourceId _tableId) internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config (using the specified store).
   */
  function register(IStore _store, ResourceId _tableId) internal {
    _store.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get augmentName.
   */
  function getAugmentName(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (bytes16 augmentName) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes16(_blob));
  }

  /**
   * @notice Get augmentName.
   */
  function _getAugmentName(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (bytes16 augmentName) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes16(_blob));
  }

  /**
   * @notice Get augmentName (using the specified store).
   */
  function getAugmentName(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (bytes16 augmentName) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes16(_blob));
  }

  /**
   * @notice Get augmentName.
   */
  function get(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (bytes16 augmentName) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes16(_blob));
  }

  /**
   * @notice Get augmentName.
   */
  function _get(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (bytes16 augmentName) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes16(_blob));
  }

  /**
   * @notice Get augmentName (using the specified store).
   */
  function get(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash
  ) internal view returns (bytes16 augmentName) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes16(_blob));
  }

  /**
   * @notice Set augmentName.
   */
  function setAugmentName(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    bytes16 augmentName
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((augmentName)), _fieldLayout);
  }

  /**
   * @notice Set augmentName.
   */
  function _setAugmentName(
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    bytes16 augmentName
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((augmentName)), _fieldLayout);
  }

  /**
   * @notice Set augmentName (using the specified store).
   */
  function setAugmentName(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    bytes16 augmentName
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    _store.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((augmentName)), _fieldLayout);
  }

  /**
   * @notice Set augmentName.
   */
  function set(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash, bytes16 augmentName) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((augmentName)), _fieldLayout);
  }

  /**
   * @notice Set augmentName.
   */
  function _set(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash, bytes16 augmentName) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((augmentName)), _fieldLayout);
  }

  /**
   * @notice Set augmentName (using the specified store).
   */
  function set(
    IStore _store,
    ResourceId _tableId,
    address augmentAddress,
    bytes32 argumentsHash,
    bytes16 augmentName
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    _store.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((augmentName)), _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys (using the specified store).
   */
  function deleteRecord(IStore _store, ResourceId _tableId, address augmentAddress, bytes32 argumentsHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    _store.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(bytes16 augmentName) internal pure returns (bytes memory) {
    return abi.encodePacked(augmentName);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dyanmic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(bytes16 augmentName) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(augmentName);

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(address augmentAddress, bytes32 argumentsHash) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(augmentAddress)));
    _keyTuple[1] = argumentsHash;

    return _keyTuple;
  }
}
