/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/common";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Name: (() => {
      const tableId = new TableId("geoweb", "Name");
      return defineComponent(
        world,
        {
          value: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHex(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Url: (() => {
      const tableId = new TableId("geoweb", "Url");
      return defineComponent(
        world,
        {
          value: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHex(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    MediaObject: (() => {
      const tableId = new TableId("geoweb", "MediaObject");
      return defineComponent(
        world,
        {
          name: RecsType.String,
          mediaType: RecsType.String,
          contentHash: RecsType.BigInt,
          contentSize: RecsType.BigInt,
          encodingFormat: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHex(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
