// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum ImageEncodingFormat {
  Jpeg,
  Png,
  Svg
}

enum ModelEncodingFormat {
  Glb,
  Usdz
}

enum AudioEncodingFormat {
  Mpeg,
  Mp4,
  Mp3
}

enum VideoEncodingFormat {
  Mpeg,
  Mp4,
  Mp3
}
