// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PCOOwnership, PCOOwnershipData } from "./../modules/pcoownership/tables/PCOOwnership.sol";
import { Augments, AugmentsData } from "./../modules/augmentinstall/tables/Augments.sol";
import { NameCom } from "./tables/NameCom.sol";
import { ModelCom, ModelComData } from "./tables/ModelCom.sol";
import { PositionCom, PositionComData } from "./tables/PositionCom.sol";
import { OrientationCom, OrientationComData } from "./tables/OrientationCom.sol";
import { ScaleCom, ScaleComData } from "./tables/ScaleCom.sol";
import { GeoAnchorCom, GeoAnchorComData } from "./tables/GeoAnchorCom.sol";
