// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { ModelComponent, ModelComponentData, ModelComponentTableId } from "./tables/ModelComponent.sol";
import { ImageComponent, ImageComponentData, ImageComponentTableId } from "./tables/ImageComponent.sol";
import { AudioComponent, AudioComponentData, AudioComponentTableId } from "./tables/AudioComponent.sol";
import { VideoComponent, VideoComponentData, VideoComponentTableId } from "./tables/VideoComponent.sol";
import { PositionComponent, PositionComponentData, PositionComponentTableId } from "./tables/PositionComponent.sol";
import { OrientationQuaternionComponent, OrientationQuaternionComponentData, OrientationQuaternionComponentTableId } from "./tables/OrientationQuaternionComponent.sol";
import { ScaleComponent, ScaleComponentData, ScaleComponentTableId } from "./tables/ScaleComponent.sol";
import { TrackedImageComponent, TrackedImageComponentData, TrackedImageComponentTableId } from "./tables/TrackedImageComponent.sol";
