// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { PCOOwnership, PCOOwnershipData } from "./../modules/pcoownership/tables/PCOOwnership.sol";
import { InstalledAugments } from "./../modules/augmentinstallation/tables/InstalledAugments.sol";
import { NameCom } from "./tables/NameCom.sol";
import { ModelCom, ModelComData } from "./tables/ModelCom.sol";
import { ImageCom, ImageComData } from "./tables/ImageCom.sol";
import { AudioCom, AudioComData } from "./tables/AudioCom.sol";
import { VideoCom, VideoComData } from "./tables/VideoCom.sol";
import { PositionCom, PositionComData } from "./tables/PositionCom.sol";
import { OrientationCom, OrientationComData } from "./tables/OrientationCom.sol";
import { ScaleCom, ScaleComData } from "./tables/ScaleCom.sol";
import { TrackedImageCom, TrackedImageComData } from "./tables/TrackedImageCom.sol";
