// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Name, NameTableId } from "./tables/Name.sol";
import { Url, UrlTableId } from "./tables/Url.sol";
import { MediaObject, MediaObjectData, MediaObjectTableId } from "./tables/MediaObject.sol";
import { PositionComponent, PositionComponentData, PositionComponentTableId } from "./tables/PositionComponent.sol";
import { ScaleComponent, ScaleComponentData, ScaleComponentTableId } from "./tables/ScaleComponent.sol";
import { OrientationComponent, OrientationComponentData, OrientationComponentTableId } from "./tables/OrientationComponent.sol";
import { ModelComponent, ModelComponentData, ModelComponentTableId } from "./tables/ModelComponent.sol";
import { TrackedImageComponent, TrackedImageComponentData, TrackedImageComponentTableId } from "./tables/TrackedImageComponent.sol";
import { AnchorComponent, AnchorComponentData, AnchorComponentTableId } from "./tables/AnchorComponent.sol";
