// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Name, NameTableId } from "./tables/Name.sol";
import { Url, UrlTableId } from "./tables/Url.sol";
