// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum MediaObjectType {
  Image,
  Audio,
  Video,
  Model
}

enum MediaObjectEncodingFormat {
  Glb,
  Usdz,
  Gif,
  Jpeg,
  Png,
  Svg,
  Mpeg,
  Mp4,
  Mp3
}

enum ImageEncodingFormat {
  Jpeg,
  Png,
  Svg
}

enum ModelEncodingFormat {
  Glb,
  Usdz
}
