// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { TrackedImageComponentData, PositionComponentData, ScaleComponentData } from "./../Tables.sol";

interface IARSystem {
  function geoweb_ARSystem_addNewImageAnchor(
    TrackedImageComponentData memory trackedImageComponentData
  ) external returns (bytes32 key);

  function geoweb_ARSystem_addNewObject(
    bytes32 anchor,
    PositionComponentData memory positionComponentData,
    ScaleComponentData memory scaleComponentData,
    bytes memory usdz
  ) external returns (bytes32 key);
}
