// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { PositionComponentData } from "./../Tables.sol";

interface IARSystem {
  function geoweb_ARSystem_addNewAnchor(PositionComponentData memory positionData) external returns (bytes32 key);

  function geoweb_ARSystem_addNewObject(bytes32 anchor, bytes memory usdz) external returns (bytes32 key);
}
