// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IAugment } from "./../../modules/augmentinstallation/IAugment.sol";

/**
 * @title IAugmentInstallationSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAugmentInstallationSystem {
  function installAugment(IAugment augment, bytes14 namespace, bytes calldata args) external;
}
