// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MediaObjectData } from "./../Tables.sol";

interface IMediaGallerySystem {
  function geoweb_MediaGallerySyst_addToMediaGallery(
    MediaObjectData memory mediaObjectData
  ) external returns (bytes32 key);

  function geoweb_MediaGallerySyst_removeFromMediaGallery(bytes32 key) external;
}
