// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IProfileSystem {
  function geoweb_ProfileSystem_setName(string calldata name) external;

  function geoweb_ProfileSystem_setUrl(string calldata url) external;
}
